my @ignore_list_final = ();

sub create_ignore_list() {
    push @ignore_list_final, qr/^lookup_ip_acl/;
    push @ignore_list_final, qr/^lookup_acl/;
    push @ignore_list_final, qr/^lookup_hash/;
    push @ignore_list_final, qr/^lookup_re/;
    push @ignore_list_final, qr/^lookup_ldap/;
    push @ignore_list_final, qr/^lookup_sql_field.* result=[YN]$/;
    push @ignore_list_final, qr/^lookup .* does not match$/;
    push @ignore_list_final, qr/^lookup [[(]/;
    push @ignore_list_final, qr/^lookup => /;
    push @ignore_list_final, qr/^lookup: /;
    push @ignore_list_final, qr/^save_info_preliminary/; # log level 4
    push @ignore_list_final, qr/^save_info_final/;       # log level 4
    push @ignore_list_final, qr/^sql: /;
    push @ignore_list_final, qr/^sql_storage: retrying/;
    push @ignore_list_final, qr/^sql flush: /;
    push @ignore_list_final, qr/^sql print/;
    push @ignore_list_final, qr/^sql begin transaction/;
    push @ignore_list_final, qr/^sql rollback/;
    push @ignore_list_final, qr/^mail_via_sql: /;
    push @ignore_list_final, qr/^CALLING SA check$/;
    push @ignore_list_final, qr/^calling SA parse,/;
    push @ignore_list_final, qr/^timer set to \d+/;
    push @ignore_list_final, qr/^query_keys/;
    push @ignore_list_final, qr/^find_or_save_addr: /;
    push @ignore_list_final, qr/^header: /;
    push @ignore_list_final, qr/^DO_QUARANTINE, /;
    push @ignore_list_final, qr/^DEBUG_ONESHOT: /;
    push @ignore_list_final, qr/^TempDir::/;
    push @ignore_list_final, qr/^check_mail_begin_task: /;
    push @ignore_list_final, qr/^program: .*?(anomy|altermime|disclaimer).*? said: /; # log_level 2
    push @ignore_list_final, qr/^body (?:type|hash): /;
    push @ignore_list_final, qr/^\d+\.From: <.*>, \d+.Mail_From:/;
    push @ignore_list_final, qr/^The amavisd daemon is (?:apparently )?not running/;
    push @ignore_list_final, qr/^rw_loop/;
    push @ignore_list_final, qr/^[SL]MTP[><]/;
    push @ignore_list_final, qr/^[SL]MTP response for/;
    push @ignore_list_final, qr/^dsn:/i, # DSN or dsn
        push @ignore_list_final, qr/^enqueue: /;
    push @ignore_list_final, qr/^write_header: /;
    push @ignore_list_final, qr/^banned check: /;
    push @ignore_list_final, qr/^child_finish_hook/;
    push @ignore_list_final, qr/^inspect_dsn:/;
    push @ignore_list_final, qr/^client IP address unknown/;
    push @ignore_list_final, qr/^final_destiny/;
    push @ignore_list_final, qr/^one_response_for_all/;
    push @ignore_list_final, qr/^headers CLUSTERING/;
    push @ignore_list_final, qr/^notif=/;
    push @ignore_list_final, qr/^\(about to connect/;
    push @ignore_list_final, qr/^Original mail size/;
    push @ignore_list_final, qr/^TempDir removal/;
    push @ignore_list_final, qr/^Issued a new file name/;
    push @ignore_list_final, qr/^starting banned checks/;
    push @ignore_list_final, qr/^skip admin notification/;
    push @ignore_list_final, qr/^do_notify_and_quarantine - done/;
    push @ignore_list_final, qr/^do_[a-zA-Z]+.* done$/i;
    push @ignore_list_final, qr/^Remote host presents itself as:/;
    push @ignore_list_final, qr/^connect_to_ldap/;
    push @ignore_list_final, qr/^connect_to_sql: trying /;
    push @ignore_list_final, qr/^ldap begin_work/;
    push @ignore_list_final, qr/^Connecting to LDAP server/;
    push @ignore_list_final, qr/^loaded base policy bank/;
    push @ignore_list_final, qr/^\d+\.From:/;
    push @ignore_list_final, qr/^Syslog (retries|warnings)/;
    push @ignore_list_final, qr/^smtp connection cache/;
    push @ignore_list_final, qr/^smtp cmd> /;
    push @ignore_list_final, qr/^smtp session/;
    push @ignore_list_final, qr/^Ignoring stale PID file/;
    push @ignore_list_final, qr/^mime_decode_preamble/;
    push @ignore_list_final, qr/^doing banned check for/;
    push @ignore_list_final, qr/^open_on_specific_fd/;
    push @ignore_list_final, qr/^reparenting /;
    push @ignore_list_final, qr/^Issued a new pseudo part: /;
    push @ignore_list_final, qr/^run_command: /;
    push @ignore_list_final, qr/^result line from file/;
    push @ignore_list_final, qr/^Charging /;
    push @ignore_list_final, qr/^check_for_banned /;
    push @ignore_list_final, qr/^Extracting mime components$/;
    push @ignore_list_final, qr/^response to /;
    push @ignore_list_final, qr/^File-type of /;
    push @ignore_list_final, qr/^Skip admin notification, /;
    push @ignore_list_final, qr/^run_av: /;
    push @ignore_list_final, qr/^string_to_mime_entity /;
    push @ignore_list_final, qr/^ndn_needed=/;
    push @ignore_list_final, qr/^sending RCPT TO:/;
    push @ignore_list_final, qr/^decode_parts: /;
    push @ignore_list_final, qr/^decompose_part: /;
    push @ignore_list_final, qr/^setting body type: /;
    push @ignore_list_final, qr/^mime_decode_epilogue: /;
    push @ignore_list_final, qr/^string_to_mime_entity: /;
    push @ignore_list_final, qr/^at the END handler: /;
    push @ignore_list_final, qr/^Amavis::.* called$/;
    push @ignore_list_final, qr/^Amavis::.* close,/;
    push @ignore_list_final, qr/^dkim: /; # XXX provide stats
    push @ignore_list_final, qr/^collect banned table/;
    push @ignore_list_final, qr/^collect_results from/;
    push @ignore_list_final, qr/^blocking contents category is/;
    push @ignore_list_final, qr/^running file\(/;
    push @ignore_list_final, qr/^Found av scanner/;
    push @ignore_list_final, qr/^Found myself/;
    push @ignore_list_final, qr/^mail_via_smtp/;
    push @ignore_list_final, qr/^switch_to_client_time/;
    push @ignore_list_final, qr/^parse_message_id/;
    push @ignore_list_final, qr/^parse_received: /;
    push @ignore_list_final, qr/^parse_ip_address_from_received: /;
    push @ignore_list_final, qr/^fish_out_ip_from_received: /;
    push @ignore_list_final, qr/^Waiting for the process \S+ to terminate/;
    push @ignore_list_final, qr/^Valid PID file \(younger than sys uptime/;
    push @ignore_list_final, qr/^Sending SIG\S+ to amavisd/;
    push @ignore_list_final, qr/^Can't send SIG\S+ to process/;
    push @ignore_list_final, qr/^killing process/;
    push @ignore_list_final, qr/^no need to kill process/;
    push @ignore_list_final, qr/^process .* is still alive/;
    push @ignore_list_final, qr/^Daemon \[\d+\] terminated by SIG/;
    push @ignore_list_final, qr/^storage and lookups will use .* to SQL/;
    push @ignore_list_final, qr/^idle_proc, /;
    push @ignore_list_final, qr/^switch_to_my_time/;
    push @ignore_list_final, qr/^TempDir::strip: /;
    push @ignore_list_final, qr/^rmdir_recursively/;
    push @ignore_list_final, qr/^sending [SL]MTP response/;
    push @ignore_list_final, qr/^prolong_timer/;
    push @ignore_list_final, qr/^process_request:/;
    push @ignore_list_final, qr/^exiting process_request/;
    push @ignore_list_final, qr/^post_process_request_hook: /;
    push @ignore_list_final, qr/^SMTP session over/;
    push @ignore_list_final, qr/^updating snmp variables/;
    push @ignore_list_final, qr/^best_try_originator_ip/;
    push @ignore_list_final, qr/^mail checking ended: /; # log level 2
    push @ignore_list_final, qr/^The amavisd daemon is already running/;
    push @ignore_list_final, qr/^AUTH not needed/;
    push @ignore_list_final, qr/^load: \d+ %, total idle/;
    push @ignore_list_final, qr/^policy protocol: [^=]+=\S+(?:,\S+)*$/; # allow "policy protocol: INVALID ..." later
    push @ignore_list_final, qr/^penpals: /;
    push @ignore_list_final, qr/^Not calling virus scanners, no files to scan in/;
    push @ignore_list_final, qr/^local delivery: /;
    push @ignore_list_final, qr/^run_as_subprocess: child process \S*: Broken pipe/;
    push @ignore_list_final, qr/^initializing Mail::SpamAssassin/;
    push @ignore_list_final, qr/^Error reading mail header section/; # seems to occur gen. due to perl getline() bug
    push @ignore_list_final, qr/^flatten_and_tidy_dir/;
    push @ignore_list_final, qr/^do_7zip: member/;
    push @ignore_list_final, qr/^Expanding \S+ archive/;
    push @ignore_list_final, qr/^files_to_scan:/;
    push @ignore_list_final, qr/^Unzipping p\d+/;
    push @ignore_list_final, qr/^writing mail text to SQL/;
    push @ignore_list_final, qr/^strip_tempdir/;
    push @ignore_list_final, qr/^no parts, file/;
    push @ignore_list_final, qr/^warnsender_with_pass/;
    push @ignore_list_final, qr/^RETURNED FROM SA check/;
    push @ignore_list_final, qr/^mime_traverse: /;
    push @ignore_list_final, qr/^do_spam: /;
    push @ignore_list_final, qr/^prepare_tempdir: /;
    push @ignore_list_final, qr/^check_header: /;
    push @ignore_list_final, qr/^skip admin notification/;
    push @ignore_list_final, qr/^do_executable: not a/;
    push @ignore_list_final, qr/^Skip spam admin notification, no administrators$/;
    push @ignore_list_final, qr/^skip banned check for/;
    push @ignore_list_final, qr/^is_outgoing /;
    push @ignore_list_final, qr/^NO Disclaimer/;
    push @ignore_list_final, qr/^Using \(\S+\) on file/;
    push @ignore_list_final, qr/^no anti-spam code loaded/;
    push @ignore_list_final, qr/^entered child_init_hook/;
    push @ignore_list_final, qr/^body type/;
    push @ignore_list_final, qr/^establish_or_refresh/;
    push @ignore_list_final, qr/^get_body_digest/;
    push @ignore_list_final, qr/^ask_daemon_internal/;
    push @ignore_list_final, qr/^Turning AV infection into a spam report, name already accounted for/;
    push @ignore_list_final, qr/^Calling virus scanners/;
    push @ignore_list_final, qr/^timer stopped after /;
    push @ignore_list_final, qr/^virus_presence /;
    push @ignore_list_final, qr/^cache entry /;
    push @ignore_list_final, qr/^generate_mail_id /;
    push @ignore_list_final, qr/^Load low precedence policybank/;
    push @ignore_list_final, qr/^warm restart on /; # XXX could be placed instartup info
    push @ignore_list_final, qr/^Signalling a SIGHUP to a running daemon/;
    push @ignore_list_final, qr/^Deleting db files /;
    push @ignore_list_final, qr/^address modified \(/;
    push @ignore_list_final, qr/^Request: AM\.PDP /;
    push @ignore_list_final, qr/^DSPAM result: /;
    push @ignore_list_final, qr/^bind to \//;
    push @ignore_list_final, qr/^ZMQ enabled: /;

    push @ignore_list_final, qr/^Inserting header field: X-Amavis-Hold: /;
    push @ignore_list_final, qr/^Decoding of .* failed, leaving it unpacked: /;

    # various forms of "Using ..."
    # more specific, interesting variants already captured: search "Using"
    push @ignore_list_final, qr/^Using \(.*\) on dir:/;
    push @ignore_list_final, qr/^Using [^:]+: \(built-in interface\)/;
    push @ignore_list_final, qr/^Using \(.*\): /;
    push @ignore_list_final, qr/: sleeping for /;
    push @ignore_list_final, qr/creating socket by /;

    # unanchored
    push @ignore_list_final, qr/\bRUSAGE\b/;
    push @ignore_list_final, qr/: Sending .* to UNIX socket/;
    push @ignore_list_final, qr/^lookup_ip_acl/;
    push @ignore_list_final, qr/^lookup_acl/;
    push @ignore_list_final, qr/^lookup_hash/;
    push @ignore_list_final, qr/^lookup_re/;
    push @ignore_list_final, qr/^lookup_ldap/;
    push @ignore_list_final, qr/^lookup_sql_field.* result=[YN]$/;
    push @ignore_list_final, qr/^lookup .* does not match$/;
    push @ignore_list_final, qr/^lookup [[(]/;
    push @ignore_list_final, qr/^lookup => /;
    push @ignore_list_final, qr/^lookup: /;
    push @ignore_list_final, qr/^save_info_preliminary/; # log level 4
    push @ignore_list_final, qr/^save_info_final/;       # log level 4
    push @ignore_list_final, qr/^sql: /;
    push @ignore_list_final, qr/^sql_storage: retrying/;
    push @ignore_list_final, qr/^sql flush: /;
    push @ignore_list_final, qr/^sql print/;
    push @ignore_list_final, qr/^sql begin transaction/;
    push @ignore_list_final, qr/^sql rollback/;
    push @ignore_list_final, qr/^mail_via_sql: /;
    push @ignore_list_final, qr/^CALLING SA check$/;
    push @ignore_list_final, qr/^calling SA parse,/;
    push @ignore_list_final, qr/^timer set to \d+/;
    push @ignore_list_final, qr/^query_keys/;
    push @ignore_list_final, qr/^find_or_save_addr: /;
    push @ignore_list_final, qr/^header: /;
    push @ignore_list_final, qr/^DO_QUARANTINE, /;
    push @ignore_list_final, qr/^DEBUG_ONESHOT: /;
    push @ignore_list_final, qr/^TempDir::/;
    push @ignore_list_final, qr/^check_mail_begin_task: /;
    push @ignore_list_final, qr/^program: .*?(anomy|altermime|disclaimer).*? said: /; # log_level 2
    push @ignore_list_final, qr/^body (?:type|hash): /;
    push @ignore_list_final, qr/^\d+\.From: <.*>, \d+.Mail_From:/;
    push @ignore_list_final, qr/^The amavisd daemon is (?:apparently )?not running/;
    push @ignore_list_final, qr/^rw_loop/;
    push @ignore_list_final, qr/^[SL]MTP[><]/;
    push @ignore_list_final, qr/^[SL]MTP response for/;
    push @ignore_list_final, qr/^dsn:/i, # DSN or dsn
        push @ignore_list_final, qr/^enqueue: /;
    push @ignore_list_final, qr/^write_header: /;
    push @ignore_list_final, qr/^banned check: /;
    push @ignore_list_final, qr/^child_finish_hook/;
    push @ignore_list_final, qr/^inspect_dsn:/;
    push @ignore_list_final, qr/^client IP address unknown/;
    push @ignore_list_final, qr/^final_destiny/;
    push @ignore_list_final, qr/^one_response_for_all/;
    push @ignore_list_final, qr/^headers CLUSTERING/;
    push @ignore_list_final, qr/^notif=/;
    push @ignore_list_final, qr/^\(about to connect/;
    push @ignore_list_final, qr/^Original mail size/;
    push @ignore_list_final, qr/^TempDir removal/;
    push @ignore_list_final, qr/^Issued a new file name/;
    push @ignore_list_final, qr/^starting banned checks/;
    push @ignore_list_final, qr/^skip admin notification/;
    push @ignore_list_final, qr/^do_notify_and_quarantine - done/;
    push @ignore_list_final, qr/^do_[a-zA-Z]+.* done$/i;
    push @ignore_list_final, qr/^Remote host presents itself as:/;
    push @ignore_list_final, qr/^connect_to_ldap/;
    push @ignore_list_final, qr/^connect_to_sql: trying /;
    push @ignore_list_final, qr/^ldap begin_work/;
    push @ignore_list_final, qr/^Connecting to LDAP server/;
    push @ignore_list_final, qr/^loaded base policy bank/;
    push @ignore_list_final, qr/^\d+\.From:/;
    push @ignore_list_final, qr/^Syslog (retries|warnings)/;
    push @ignore_list_final, qr/^smtp connection cache/;
    push @ignore_list_final, qr/^smtp cmd> /;
    push @ignore_list_final, qr/^smtp session/;
    push @ignore_list_final, qr/^Ignoring stale PID file/;
    push @ignore_list_final, qr/^mime_decode_preamble/;
    push @ignore_list_final, qr/^doing banned check for/;
    push @ignore_list_final, qr/^open_on_specific_fd/;
    push @ignore_list_final, qr/^reparenting /;
    push @ignore_list_final, qr/^Issued a new pseudo part: /;
    push @ignore_list_final, qr/^run_command: /;
    push @ignore_list_final, qr/^result line from file/;
    push @ignore_list_final, qr/^Charging /;
    push @ignore_list_final, qr/^check_for_banned /;
    push @ignore_list_final, qr/^Extracting mime components$/;
    push @ignore_list_final, qr/^response to /;
    push @ignore_list_final, qr/^File-type of /;
    push @ignore_list_final, qr/^Skip admin notification, /;
    push @ignore_list_final, qr/^run_av: /;
    push @ignore_list_final, qr/^string_to_mime_entity /;
    push @ignore_list_final, qr/^ndn_needed=/;
    push @ignore_list_final, qr/^sending RCPT TO:/;
    push @ignore_list_final, qr/^decode_parts: /;
    push @ignore_list_final, qr/^decompose_part: /;
    push @ignore_list_final, qr/^setting body type: /;
    push @ignore_list_final, qr/^mime_decode_epilogue: /;
    push @ignore_list_final, qr/^string_to_mime_entity: /;
    push @ignore_list_final, qr/^at the END handler: /;
    push @ignore_list_final, qr/^Amavis::.* called$/;
    push @ignore_list_final, qr/^Amavis::.* close,/;
    push @ignore_list_final, qr/^dkim: /; # XXX provide stats
    push @ignore_list_final, qr/^collect banned table/;
    push @ignore_list_final, qr/^collect_results from/;
    push @ignore_list_final, qr/^blocking contents category is/;
    push @ignore_list_final, qr/^running file\(/;
    push @ignore_list_final, qr/^Found av scanner/;
    push @ignore_list_final, qr/^Found myself/;
    push @ignore_list_final, qr/^mail_via_smtp/;
    push @ignore_list_final, qr/^switch_to_client_time/;
    push @ignore_list_final, qr/^parse_message_id/;
    push @ignore_list_final, qr/^parse_received: /;
    push @ignore_list_final, qr/^parse_ip_address_from_received: /;
    push @ignore_list_final, qr/^fish_out_ip_from_received: /;
    push @ignore_list_final, qr/^Waiting for the process \S+ to terminate/;
    push @ignore_list_final, qr/^Valid PID file \(younger than sys uptime/;
    push @ignore_list_final, qr/^Sending SIG\S+ to amavisd/;
    push @ignore_list_final, qr/^Can't send SIG\S+ to process/;
    push @ignore_list_final, qr/^killing process/;
    push @ignore_list_final, qr/^no need to kill process/;
    push @ignore_list_final, qr/^process .* is still alive/;
    push @ignore_list_final, qr/^Daemon \[\d+\] terminated by SIG/;
    push @ignore_list_final, qr/^storage and lookups will use .* to SQL/;
    push @ignore_list_final, qr/^idle_proc, /;
    push @ignore_list_final, qr/^switch_to_my_time/;
    push @ignore_list_final, qr/^TempDir::strip: /;
    push @ignore_list_final, qr/^rmdir_recursively/;
    push @ignore_list_final, qr/^sending [SL]MTP response/;
    push @ignore_list_final, qr/^prolong_timer/;
    push @ignore_list_final, qr/^process_request:/;
    push @ignore_list_final, qr/^exiting process_request/;
    push @ignore_list_final, qr/^post_process_request_hook: /;
    push @ignore_list_final, qr/^SMTP session over/;
    push @ignore_list_final, qr/^updating snmp variables/;
    push @ignore_list_final, qr/^best_try_originator_ip/;
    push @ignore_list_final, qr/^mail checking ended: /; # log level 2
    push @ignore_list_final, qr/^The amavisd daemon is already running/;
    push @ignore_list_final, qr/^AUTH not needed/;
    push @ignore_list_final, qr/^load: \d+ %, total idle/;
    push @ignore_list_final, qr/^policy protocol: [^=]+=\S+(?:,\S+)*$/; # allow "policy protocol: INVALID ..." later
    push @ignore_list_final, qr/^penpals: /;
    push @ignore_list_final, qr/^Not calling virus scanners, no files to scan in/;
    push @ignore_list_final, qr/^local delivery: /;
    push @ignore_list_final, qr/^run_as_subprocess: child process \S*: Broken pipe/;
    push @ignore_list_final, qr/^initializing Mail::SpamAssassin/;
    push @ignore_list_final, qr/^Error reading mail header section/; # seems to occur gen. due to perl getline() bug
    push @ignore_list_final, qr/^flatten_and_tidy_dir/;
    push @ignore_list_final, qr/^do_7zip: member/;
    push @ignore_list_final, qr/^Expanding \S+ archive/;
    push @ignore_list_final, qr/^files_to_scan:/;
    push @ignore_list_final, qr/^Unzipping p\d+/;
    push @ignore_list_final, qr/^writing mail text to SQL/;
    push @ignore_list_final, qr/^strip_tempdir/;
    push @ignore_list_final, qr/^no parts, file/;
    push @ignore_list_final, qr/^warnsender_with_pass/;
    push @ignore_list_final, qr/^RETURNED FROM SA check/;
    push @ignore_list_final, qr/^mime_traverse: /;
    push @ignore_list_final, qr/^do_spam: /;
    push @ignore_list_final, qr/^prepare_tempdir: /;
    push @ignore_list_final, qr/^check_header: /;
    push @ignore_list_final, qr/^skip admin notification/;
    push @ignore_list_final, qr/^do_executable: not a/;
    push @ignore_list_final, qr/^Skip spam admin notification, no administrators$/;
    push @ignore_list_final, qr/^skip banned check for/;
    push @ignore_list_final, qr/^is_outgoing /;
    push @ignore_list_final, qr/^NO Disclaimer/;
    push @ignore_list_final, qr/^Using \(\S+\) on file/;
    push @ignore_list_final, qr/^no anti-spam code loaded/;
    push @ignore_list_final, qr/^entered child_init_hook/;
    push @ignore_list_final, qr/^body type/;
    push @ignore_list_final, qr/^establish_or_refresh/;
    push @ignore_list_final, qr/^get_body_digest/;
    push @ignore_list_final, qr/^ask_daemon_internal/;
    push @ignore_list_final, qr/^Turning AV infection into a spam report, name already accounted for/;
    push @ignore_list_final, qr/^Calling virus scanners/;
    push @ignore_list_final, qr/^timer stopped after /;
    push @ignore_list_final, qr/^virus_presence /;
    push @ignore_list_final, qr/^cache entry /;
    push @ignore_list_final, qr/^generate_mail_id /;
    push @ignore_list_final, qr/^Load low precedence policybank/;
    push @ignore_list_final, qr/^warm restart on /; # XXX could be placed instartup info
    push @ignore_list_final, qr/^Signalling a SIGHUP to a running daemon/;
    push @ignore_list_final, qr/^Deleting db files /;
    push @ignore_list_final, qr/^address modified \(/;
    push @ignore_list_final, qr/^Request: AM\.PDP /;
    push @ignore_list_final, qr/^DSPAM result: /;
    push @ignore_list_final, qr/^bind to \//;
    push @ignore_list_final, qr/^ZMQ enabled: /;

    push @ignore_list_final, qr/^Inserting header field: X-Amavis-Hold: /;
    push @ignore_list_final, qr/^Decoding of .* failed, leaving it unpacked: /;

    # various forms of "Using ..."
    # more specific, interesting variants already captured: search "Using"
    push @ignore_list_final, qr/^Using \(.*\) on dir:/;
    push @ignore_list_final, qr/^Using [^:]+: \(built-in interface\)/;
    push @ignore_list_final, qr/^Using \(.*\): /;
    push @ignore_list_final, qr/: sleeping for /;
    push @ignore_list_final, qr/creating socket by /;

    # unanchored
    push @ignore_list_final, qr/\bRUSAGE\b/;
    push @ignore_list_final, qr/: Sending .* to UNIX socket/;
    push @ignore_list_final, qr/^lookup_ip_acl/;
    push @ignore_list_final, qr/^lookup_acl/;
    push @ignore_list_final, qr/^lookup_hash/;
    push @ignore_list_final, qr/^lookup_re/;
    push @ignore_list_final, qr/^lookup_ldap/;
    push @ignore_list_final, qr/^lookup_sql_field.* result=[YN]$/;
    push @ignore_list_final, qr/^lookup .* does not match$/;
    push @ignore_list_final, qr/^lookup [[(]/;
    push @ignore_list_final, qr/^lookup => /;
    push @ignore_list_final, qr/^lookup: /;
    push @ignore_list_final, qr/^save_info_preliminary/; # log level 4
    push @ignore_list_final, qr/^save_info_final/;       # log level 4
    push @ignore_list_final, qr/^sql: /;
    push @ignore_list_final, qr/^sql_storage: retrying/;
    push @ignore_list_final, qr/^sql flush: /;
    push @ignore_list_final, qr/^sql print/;
    push @ignore_list_final, qr/^sql begin transaction/;
    push @ignore_list_final, qr/^sql rollback/;
    push @ignore_list_final, qr/^mail_via_sql: /;
    push @ignore_list_final, qr/^CALLING SA check$/;
    push @ignore_list_final, qr/^calling SA parse,/;
    push @ignore_list_final, qr/^timer set to \d+/;
    push @ignore_list_final, qr/^query_keys/;
    push @ignore_list_final, qr/^find_or_save_addr: /;
    push @ignore_list_final, qr/^header: /;
    push @ignore_list_final, qr/^DO_QUARANTINE, /;
    push @ignore_list_final, qr/^DEBUG_ONESHOT: /;
    push @ignore_list_final, qr/^TempDir::/;
    push @ignore_list_final, qr/^check_mail_begin_task: /;
    push @ignore_list_final, qr/^program: .*?(anomy|altermime|disclaimer).*? said: /; # log_level 2
    push @ignore_list_final, qr/^body (?:type|hash): /;
    push @ignore_list_final, qr/^\d+\.From: <.*>, \d+.Mail_From:/;
    push @ignore_list_final, qr/^The amavisd daemon is (?:apparently )?not running/;
    push @ignore_list_final, qr/^rw_loop/;
    push @ignore_list_final, qr/^[SL]MTP[><]/;
    push @ignore_list_final, qr/^[SL]MTP response for/;
    push @ignore_list_final, qr/^dsn:/i, # DSN or dsn
        push @ignore_list_final, qr/^enqueue: /;
    push @ignore_list_final, qr/^write_header: /;
    push @ignore_list_final, qr/^banned check: /;
    push @ignore_list_final, qr/^child_finish_hook/;
    push @ignore_list_final, qr/^inspect_dsn:/;
    push @ignore_list_final, qr/^client IP address unknown/;
    push @ignore_list_final, qr/^final_destiny/;
    push @ignore_list_final, qr/^one_response_for_all/;
    push @ignore_list_final, qr/^headers CLUSTERING/;
    push @ignore_list_final, qr/^notif=/;
    push @ignore_list_final, qr/^\(about to connect/;
    push @ignore_list_final, qr/^Original mail size/;
    push @ignore_list_final, qr/^TempDir removal/;
    push @ignore_list_final, qr/^Issued a new file name/;
    push @ignore_list_final, qr/^starting banned checks/;
    push @ignore_list_final, qr/^skip admin notification/;
    push @ignore_list_final, qr/^do_notify_and_quarantine - done/;
    push @ignore_list_final, qr/^do_[a-zA-Z]+.* done$/i;
    push @ignore_list_final, qr/^Remote host presents itself as:/;
    push @ignore_list_final, qr/^connect_to_ldap/;
    push @ignore_list_final, qr/^connect_to_sql: trying /;
    push @ignore_list_final, qr/^ldap begin_work/;
    push @ignore_list_final, qr/^Connecting to LDAP server/;
    push @ignore_list_final, qr/^loaded base policy bank/;
    push @ignore_list_final, qr/^\d+\.From:/;
    push @ignore_list_final, qr/^Syslog (retries|warnings)/;
    push @ignore_list_final, qr/^smtp connection cache/;
    push @ignore_list_final, qr/^smtp cmd> /;
    push @ignore_list_final, qr/^smtp session/;
    push @ignore_list_final, qr/^Ignoring stale PID file/;
    push @ignore_list_final, qr/^mime_decode_preamble/;
    push @ignore_list_final, qr/^doing banned check for/;
    push @ignore_list_final, qr/^open_on_specific_fd/;
    push @ignore_list_final, qr/^reparenting /;
    push @ignore_list_final, qr/^Issued a new pseudo part: /;
    push @ignore_list_final, qr/^run_command: /;
    push @ignore_list_final, qr/^result line from file/;
    push @ignore_list_final, qr/^Charging /;
    push @ignore_list_final, qr/^check_for_banned /;
    push @ignore_list_final, qr/^Extracting mime components$/;
    push @ignore_list_final, qr/^response to /;
    push @ignore_list_final, qr/^File-type of /;
    push @ignore_list_final, qr/^Skip admin notification, /;
    push @ignore_list_final, qr/^run_av: /;
    push @ignore_list_final, qr/^string_to_mime_entity /;
    push @ignore_list_final, qr/^ndn_needed=/;
    push @ignore_list_final, qr/^sending RCPT TO:/;
    push @ignore_list_final, qr/^decode_parts: /;
    push @ignore_list_final, qr/^decompose_part: /;
    push @ignore_list_final, qr/^setting body type: /;
    push @ignore_list_final, qr/^mime_decode_epilogue: /;
    push @ignore_list_final, qr/^string_to_mime_entity: /;
    push @ignore_list_final, qr/^at the END handler: /;
    push @ignore_list_final, qr/^Amavis::.* called$/;
    push @ignore_list_final, qr/^Amavis::.* close,/;
    push @ignore_list_final, qr/^dkim: /; # XXX provide stats
    push @ignore_list_final, qr/^collect banned table/;
    push @ignore_list_final, qr/^collect_results from/;
    push @ignore_list_final, qr/^blocking contents category is/;
    push @ignore_list_final, qr/^running file\(/;
    push @ignore_list_final, qr/^Found av scanner/;
    push @ignore_list_final, qr/^Found myself/;
    push @ignore_list_final, qr/^mail_via_smtp/;
    push @ignore_list_final, qr/^switch_to_client_time/;
    push @ignore_list_final, qr/^parse_message_id/;
    push @ignore_list_final, qr/^parse_received: /;
    push @ignore_list_final, qr/^parse_ip_address_from_received: /;
    push @ignore_list_final, qr/^fish_out_ip_from_received: /;
    push @ignore_list_final, qr/^Waiting for the process \S+ to terminate/;
    push @ignore_list_final, qr/^Valid PID file \(younger than sys uptime/;
    push @ignore_list_final, qr/^Sending SIG\S+ to amavisd/;
    push @ignore_list_final, qr/^Can't send SIG\S+ to process/;
    push @ignore_list_final, qr/^killing process/;
    push @ignore_list_final, qr/^no need to kill process/;
    push @ignore_list_final, qr/^process .* is still alive/;
    push @ignore_list_final, qr/^Daemon \[\d+\] terminated by SIG/;
    push @ignore_list_final, qr/^storage and lookups will use .* to SQL/;
    push @ignore_list_final, qr/^idle_proc, /;
    push @ignore_list_final, qr/^switch_to_my_time/;
    push @ignore_list_final, qr/^TempDir::strip: /;
    push @ignore_list_final, qr/^rmdir_recursively/;
    push @ignore_list_final, qr/^sending [SL]MTP response/;
    push @ignore_list_final, qr/^prolong_timer/;
    push @ignore_list_final, qr/^process_request:/;
    push @ignore_list_final, qr/^exiting process_request/;
    push @ignore_list_final, qr/^post_process_request_hook: /;
    push @ignore_list_final, qr/^SMTP session over/;
    push @ignore_list_final, qr/^updating snmp variables/;
    push @ignore_list_final, qr/^best_try_originator_ip/;
    push @ignore_list_final, qr/^mail checking ended: /; # log level 2
    push @ignore_list_final, qr/^The amavisd daemon is already running/;
    push @ignore_list_final, qr/^AUTH not needed/;
    push @ignore_list_final, qr/^load: \d+ %, total idle/;
    push @ignore_list_final, qr/^policy protocol: [^=]+=\S+(?:,\S+)*$/; # allow "policy protocol: INVALID ..." later
    push @ignore_list_final, qr/^penpals: /;
    push @ignore_list_final, qr/^Not calling virus scanners, no files to scan in/;
    push @ignore_list_final, qr/^local delivery: /;
    push @ignore_list_final, qr/^run_as_subprocess: child process \S*: Broken pipe/;
    push @ignore_list_final, qr/^initializing Mail::SpamAssassin/;
    push @ignore_list_final, qr/^Error reading mail header section/; # seems to occur gen. due to perl getline() bug
    push @ignore_list_final, qr/^flatten_and_tidy_dir/;
    push @ignore_list_final, qr/^do_7zip: member/;
    push @ignore_list_final, qr/^Expanding \S+ archive/;
    push @ignore_list_final, qr/^files_to_scan:/;
    push @ignore_list_final, qr/^Unzipping p\d+/;
    push @ignore_list_final, qr/^writing mail text to SQL/;
    push @ignore_list_final, qr/^strip_tempdir/;
    push @ignore_list_final, qr/^no parts, file/;
    push @ignore_list_final, qr/^warnsender_with_pass/;
    push @ignore_list_final, qr/^RETURNED FROM SA check/;
    push @ignore_list_final, qr/^mime_traverse: /;
    push @ignore_list_final, qr/^do_spam: /;
    push @ignore_list_final, qr/^prepare_tempdir: /;
    push @ignore_list_final, qr/^check_header: /;
    push @ignore_list_final, qr/^skip admin notification/;
    push @ignore_list_final, qr/^do_executable: not a/;
    push @ignore_list_final, qr/^Skip spam admin notification, no administrators$/;
    push @ignore_list_final, qr/^skip banned check for/;
    push @ignore_list_final, qr/^is_outgoing /;
    push @ignore_list_final, qr/^NO Disclaimer/;
    push @ignore_list_final, qr/^Using \(\S+\) on file/;
    push @ignore_list_final, qr/^no anti-spam code loaded/;
    push @ignore_list_final, qr/^entered child_init_hook/;
    push @ignore_list_final, qr/^body type/;
    push @ignore_list_final, qr/^establish_or_refresh/;
    push @ignore_list_final, qr/^get_body_digest/;
    push @ignore_list_final, qr/^ask_daemon_internal/;
    push @ignore_list_final, qr/^Turning AV infection into a spam report, name already accounted for/;
    push @ignore_list_final, qr/^Calling virus scanners/;
    push @ignore_list_final, qr/^timer stopped after /;
    push @ignore_list_final, qr/^virus_presence /;
    push @ignore_list_final, qr/^cache entry /;
    push @ignore_list_final, qr/^generate_mail_id /;
    push @ignore_list_final, qr/^Load low precedence policybank/;
    push @ignore_list_final, qr/^warm restart on /; # XXX could be placed instartup info
    push @ignore_list_final, qr/^Signalling a SIGHUP to a running daemon/;
    push @ignore_list_final, qr/^Deleting db files /;
    push @ignore_list_final, qr/^address modified \(/;
    push @ignore_list_final, qr/^Request: AM\.PDP /;
    push @ignore_list_final, qr/^DSPAM result: /;
    push @ignore_list_final, qr/^bind to \//;
    push @ignore_list_final, qr/^ZMQ enabled: /;

    push @ignore_list_final, qr/^Inserting header field: X-Amavis-Hold: /;
    push @ignore_list_final, qr/^Decoding of .* failed, leaving it unpacked: /;

    # various forms of "Using ..."
    # more specific, interesting variants already captured: search "Using"
    push @ignore_list_final, qr/^Using \(.*\) on dir:/;
    push @ignore_list_final, qr/^Using [^:]+: \(built-in interface\)/;
    push @ignore_list_final, qr/^Using \(.*\): /;
    push @ignore_list_final, qr/: sleeping for /;
    push @ignore_list_final, qr/creating socket by /;

    # unanchored
    push @ignore_list_final, qr/\bRUSAGE\b/;
    push @ignore_list_final, qr/: Sending .* to UNIX socket/;
    push @ignore_list_final, qr/^lookup_ip_acl/;
    push @ignore_list_final, qr/^lookup_acl/;
    push @ignore_list_final, qr/^lookup_hash/;
    push @ignore_list_final, qr/^lookup_re/;
    push @ignore_list_final, qr/^lookup_ldap/;
    push @ignore_list_final, qr/^lookup_sql_field.* result=[YN]$/;
    push @ignore_list_final, qr/^lookup .* does not match$/;
    push @ignore_list_final, qr/^lookup [[(]/;
    push @ignore_list_final, qr/^lookup => /;
    push @ignore_list_final, qr/^lookup: /;
    push @ignore_list_final, qr/^save_info_preliminary/; # log level 4
    push @ignore_list_final, qr/^save_info_final/;       # log level 4
    push @ignore_list_final, qr/^sql: /;
    push @ignore_list_final, qr/^sql_storage: retrying/;
    push @ignore_list_final, qr/^sql flush: /;
    push @ignore_list_final, qr/^sql print/;
    push @ignore_list_final, qr/^sql begin transaction/;
    push @ignore_list_final, qr/^sql rollback/;
    push @ignore_list_final, qr/^mail_via_sql: /;
    push @ignore_list_final, qr/^CALLING SA check$/;
    push @ignore_list_final, qr/^calling SA parse,/;
    push @ignore_list_final, qr/^timer set to \d+/;
    push @ignore_list_final, qr/^query_keys/;
    push @ignore_list_final, qr/^find_or_save_addr: /;
    push @ignore_list_final, qr/^header: /;
    push @ignore_list_final, qr/^DO_QUARANTINE, /;
    push @ignore_list_final, qr/^DEBUG_ONESHOT: /;
    push @ignore_list_final, qr/^TempDir::/;
    push @ignore_list_final, qr/^check_mail_begin_task: /;
    push @ignore_list_final, qr/^program: .*?(anomy|altermime|disclaimer).*? said: /; # log_level 2
    push @ignore_list_final, qr/^body (?:type|hash): /;
    push @ignore_list_final, qr/^\d+\.From: <.*>, \d+.Mail_From:/;
    push @ignore_list_final, qr/^The amavisd daemon is (?:apparently )?not running/;
    push @ignore_list_final, qr/^rw_loop/;
    push @ignore_list_final, qr/^[SL]MTP[><]/;
    push @ignore_list_final, qr/^[SL]MTP response for/;
    push @ignore_list_final, qr/^dsn:/i, # DSN or dsn
        push @ignore_list_final, qr/^enqueue: /;
    push @ignore_list_final, qr/^write_header: /;
    push @ignore_list_final, qr/^banned check: /;
    push @ignore_list_final, qr/^child_finish_hook/;
    push @ignore_list_final, qr/^inspect_dsn:/;
    push @ignore_list_final, qr/^client IP address unknown/;
    push @ignore_list_final, qr/^final_destiny/;
    push @ignore_list_final, qr/^one_response_for_all/;
    push @ignore_list_final, qr/^headers CLUSTERING/;
    push @ignore_list_final, qr/^notif=/;
    push @ignore_list_final, qr/^\(about to connect/;
    push @ignore_list_final, qr/^Original mail size/;
    push @ignore_list_final, qr/^TempDir removal/;
    push @ignore_list_final, qr/^Issued a new file name/;
    push @ignore_list_final, qr/^starting banned checks/;
    push @ignore_list_final, qr/^skip admin notification/;
    push @ignore_list_final, qr/^do_notify_and_quarantine - done/;
    push @ignore_list_final, qr/^do_[a-zA-Z]+.* done$/i;
    push @ignore_list_final, qr/^Remote host presents itself as:/;
    push @ignore_list_final, qr/^connect_to_ldap/;
    push @ignore_list_final, qr/^connect_to_sql: trying /;
    push @ignore_list_final, qr/^ldap begin_work/;
    push @ignore_list_final, qr/^Connecting to LDAP server/;
    push @ignore_list_final, qr/^loaded base policy bank/;
    push @ignore_list_final, qr/^\d+\.From:/;
    push @ignore_list_final, qr/^Syslog (retries|warnings)/;
    push @ignore_list_final, qr/^smtp connection cache/;
    push @ignore_list_final, qr/^smtp cmd> /;
    push @ignore_list_final, qr/^smtp session/;
    push @ignore_list_final, qr/^Ignoring stale PID file/;
    push @ignore_list_final, qr/^mime_decode_preamble/;
    push @ignore_list_final, qr/^doing banned check for/;
    push @ignore_list_final, qr/^open_on_specific_fd/;
    push @ignore_list_final, qr/^reparenting /;
    push @ignore_list_final, qr/^Issued a new pseudo part: /;
    push @ignore_list_final, qr/^run_command: /;
    push @ignore_list_final, qr/^result line from file/;
    push @ignore_list_final, qr/^Charging /;
    push @ignore_list_final, qr/^check_for_banned /;
    push @ignore_list_final, qr/^Extracting mime components$/;
    push @ignore_list_final, qr/^response to /;
    push @ignore_list_final, qr/^File-type of /;
    push @ignore_list_final, qr/^Skip admin notification, /;
    push @ignore_list_final, qr/^run_av: /;
    push @ignore_list_final, qr/^string_to_mime_entity /;
    push @ignore_list_final, qr/^ndn_needed=/;
    push @ignore_list_final, qr/^sending RCPT TO:/;
    push @ignore_list_final, qr/^decode_parts: /;
    push @ignore_list_final, qr/^decompose_part: /;
    push @ignore_list_final, qr/^setting body type: /;
    push @ignore_list_final, qr/^mime_decode_epilogue: /;
    push @ignore_list_final, qr/^string_to_mime_entity: /;
    push @ignore_list_final, qr/^at the END handler: /;
    push @ignore_list_final, qr/^Amavis::.* called$/;
    push @ignore_list_final, qr/^Amavis::.* close,/;
    push @ignore_list_final, qr/^dkim: /; # XXX provide stats
    push @ignore_list_final, qr/^collect banned table/;
    push @ignore_list_final, qr/^collect_results from/;
    push @ignore_list_final, qr/^blocking contents category is/;
    push @ignore_list_final, qr/^running file\(/;
    push @ignore_list_final, qr/^Found av scanner/;
    push @ignore_list_final, qr/^Found myself/;
    push @ignore_list_final, qr/^mail_via_smtp/;
    push @ignore_list_final, qr/^switch_to_client_time/;
    push @ignore_list_final, qr/^parse_message_id/;
    push @ignore_list_final, qr/^parse_received: /;
    push @ignore_list_final, qr/^parse_ip_address_from_received: /;
    push @ignore_list_final, qr/^fish_out_ip_from_received: /;
    push @ignore_list_final, qr/^Waiting for the process \S+ to terminate/;
    push @ignore_list_final, qr/^Valid PID file \(younger than sys uptime/;
    push @ignore_list_final, qr/^Sending SIG\S+ to amavisd/;
    push @ignore_list_final, qr/^Can't send SIG\S+ to process/;
    push @ignore_list_final, qr/^killing process/;
    push @ignore_list_final, qr/^no need to kill process/;
    push @ignore_list_final, qr/^process .* is still alive/;
    push @ignore_list_final, qr/^Daemon \[\d+\] terminated by SIG/;
    push @ignore_list_final, qr/^storage and lookups will use .* to SQL/;
    push @ignore_list_final, qr/^idle_proc, /;
    push @ignore_list_final, qr/^switch_to_my_time/;
    push @ignore_list_final, qr/^TempDir::strip: /;
    push @ignore_list_final, qr/^rmdir_recursively/;
    push @ignore_list_final, qr/^sending [SL]MTP response/;
    push @ignore_list_final, qr/^prolong_timer/;
    push @ignore_list_final, qr/^process_request:/;
    push @ignore_list_final, qr/^exiting process_request/;
    push @ignore_list_final, qr/^post_process_request_hook: /;
    push @ignore_list_final, qr/^SMTP session over/;
    push @ignore_list_final, qr/^updating snmp variables/;
    push @ignore_list_final, qr/^best_try_originator_ip/;
    push @ignore_list_final, qr/^mail checking ended: /; # log level 2
    push @ignore_list_final, qr/^The amavisd daemon is already running/;
    push @ignore_list_final, qr/^AUTH not needed/;
    push @ignore_list_final, qr/^load: \d+ %, total idle/;
    push @ignore_list_final, qr/^policy protocol: [^=]+=\S+(?:,\S+)*$/; # allow "policy protocol: INVALID ..." later
    push @ignore_list_final, qr/^penpals: /;
    push @ignore_list_final, qr/^Not calling virus scanners, no files to scan in/;
    push @ignore_list_final, qr/^local delivery: /;
    push @ignore_list_final, qr/^run_as_subprocess: child process \S*: Broken pipe/;
    push @ignore_list_final, qr/^initializing Mail::SpamAssassin/;
    push @ignore_list_final, qr/^Error reading mail header section/; # seems to occur gen. due to perl getline() bug
    push @ignore_list_final, qr/^flatten_and_tidy_dir/;
    push @ignore_list_final, qr/^do_7zip: member/;
    push @ignore_list_final, qr/^Expanding \S+ archive/;
    push @ignore_list_final, qr/^files_to_scan:/;
    push @ignore_list_final, qr/^Unzipping p\d+/;
    push @ignore_list_final, qr/^writing mail text to SQL/;
    push @ignore_list_final, qr/^strip_tempdir/;
    push @ignore_list_final, qr/^no parts, file/;
    push @ignore_list_final, qr/^warnsender_with_pass/;
    push @ignore_list_final, qr/^RETURNED FROM SA check/;
    push @ignore_list_final, qr/^mime_traverse: /;
    push @ignore_list_final, qr/^do_spam: /;
    push @ignore_list_final, qr/^prepare_tempdir: /;
    push @ignore_list_final, qr/^check_header: /;
    push @ignore_list_final, qr/^skip admin notification/;
    push @ignore_list_final, qr/^do_executable: not a/;
    push @ignore_list_final, qr/^Skip spam admin notification, no administrators$/;
    push @ignore_list_final, qr/^skip banned check for/;
    push @ignore_list_final, qr/^is_outgoing /;
    push @ignore_list_final, qr/^NO Disclaimer/;
    push @ignore_list_final, qr/^Using \(\S+\) on file/;
    push @ignore_list_final, qr/^no anti-spam code loaded/;
    push @ignore_list_final, qr/^entered child_init_hook/;
    push @ignore_list_final, qr/^body type/;
    push @ignore_list_final, qr/^establish_or_refresh/;
    push @ignore_list_final, qr/^get_body_digest/;
    push @ignore_list_final, qr/^ask_daemon_internal/;
    push @ignore_list_final, qr/^Turning AV infection into a spam report, name already accounted for/;
    push @ignore_list_final, qr/^Calling virus scanners/;
    push @ignore_list_final, qr/^timer stopped after /;
    push @ignore_list_final, qr/^virus_presence /;
    push @ignore_list_final, qr/^cache entry /;
    push @ignore_list_final, qr/^generate_mail_id /;
    push @ignore_list_final, qr/^Load low precedence policybank/;
    push @ignore_list_final, qr/^warm restart on /; # XXX could be placed instartup info
    push @ignore_list_final, qr/^Signalling a SIGHUP to a running daemon/;
    push @ignore_list_final, qr/^Deleting db files /;
    push @ignore_list_final, qr/^address modified \(/;
    push @ignore_list_final, qr/^Request: AM\.PDP /;
    push @ignore_list_final, qr/^DSPAM result: /;
    push @ignore_list_final, qr/^bind to \//;
    push @ignore_list_final, qr/^ZMQ enabled: /;

    push @ignore_list_final, qr/^Inserting header field: X-Amavis-Hold: /;
    push @ignore_list_final, qr/^Decoding of .* failed, leaving it unpacked: /;

    # various forms of "Using ..."
    # more specific, interesting variants already captured: search "Using"
    push @ignore_list_final, qr/^Using \(.*\) on dir:/;
    push @ignore_list_final, qr/^Using [^:]+: \(built-in interface\)/;
    push @ignore_list_final, qr/^Using \(.*\): /;
    push @ignore_list_final, qr/: sleeping for /;
    push @ignore_list_final, qr/creating socket by /;

    # unanchored
    push @ignore_list_final, qr/\bRUSAGE\b/;
    push @ignore_list_final, qr/: Sending .* to UNIX socket/;
    push @ignore_list_final, qr/^lookup_ip_acl/;
    push @ignore_list_final, qr/^lookup_acl/;
    push @ignore_list_final, qr/^lookup_hash/;
    push @ignore_list_final, qr/^lookup_re/;
    push @ignore_list_final, qr/^lookup_ldap/;
    push @ignore_list_final, qr/^lookup_sql_field.* result=[YN]$/;
    push @ignore_list_final, qr/^lookup .* does not match$/;
    push @ignore_list_final, qr/^lookup [[(]/;
    push @ignore_list_final, qr/^lookup => /;
    push @ignore_list_final, qr/^lookup: /;
    push @ignore_list_final, qr/^save_info_preliminary/; # log level 4
    push @ignore_list_final, qr/^save_info_final/;       # log level 4
    push @ignore_list_final, qr/^sql: /;
    push @ignore_list_final, qr/^sql_storage: retrying/;
    push @ignore_list_final, qr/^sql flush: /;
    push @ignore_list_final, qr/^sql print/;
    push @ignore_list_final, qr/^sql begin transaction/;
    push @ignore_list_final, qr/^sql rollback/;
    push @ignore_list_final, qr/^mail_via_sql: /;
    push @ignore_list_final, qr/^CALLING SA check$/;
    push @ignore_list_final, qr/^calling SA parse,/;
    push @ignore_list_final, qr/^timer set to \d+/;
    push @ignore_list_final, qr/^query_keys/;
    push @ignore_list_final, qr/^find_or_save_addr: /;
    push @ignore_list_final, qr/^header: /;
    push @ignore_list_final, qr/^DO_QUARANTINE, /;
    push @ignore_list_final, qr/^DEBUG_ONESHOT: /;
    push @ignore_list_final, qr/^TempDir::/;
    push @ignore_list_final, qr/^check_mail_begin_task: /;
    push @ignore_list_final, qr/^program: .*?(anomy|altermime|disclaimer).*? said: /; # log_level 2
    push @ignore_list_final, qr/^body (?:type|hash): /;
    push @ignore_list_final, qr/^\d+\.From: <.*>, \d+.Mail_From:/;
    push @ignore_list_final, qr/^The amavisd daemon is (?:apparently )?not running/;
    push @ignore_list_final, qr/^rw_loop/;
    push @ignore_list_final, qr/^[SL]MTP[><]/;
    push @ignore_list_final, qr/^[SL]MTP response for/;
    push @ignore_list_final, qr/^dsn:/i, # DSN or dsn
        push @ignore_list_final, qr/^enqueue: /;
    push @ignore_list_final, qr/^write_header: /;
    push @ignore_list_final, qr/^banned check: /;
    push @ignore_list_final, qr/^child_finish_hook/;
    push @ignore_list_final, qr/^inspect_dsn:/;
    push @ignore_list_final, qr/^client IP address unknown/;
    push @ignore_list_final, qr/^final_destiny/;
    push @ignore_list_final, qr/^one_response_for_all/;
    push @ignore_list_final, qr/^headers CLUSTERING/;
    push @ignore_list_final, qr/^notif=/;
    push @ignore_list_final, qr/^\(about to connect/;
    push @ignore_list_final, qr/^Original mail size/;
    push @ignore_list_final, qr/^TempDir removal/;
    push @ignore_list_final, qr/^Issued a new file name/;
    push @ignore_list_final, qr/^starting banned checks/;
    push @ignore_list_final, qr/^skip admin notification/;
    push @ignore_list_final, qr/^do_notify_and_quarantine - done/;
    push @ignore_list_final, qr/^do_[a-zA-Z]+.* done$/i;
    push @ignore_list_final, qr/^Remote host presents itself as:/;
    push @ignore_list_final, qr/^connect_to_ldap/;
    push @ignore_list_final, qr/^connect_to_sql: trying /;
    push @ignore_list_final, qr/^ldap begin_work/;
    push @ignore_list_final, qr/^Connecting to LDAP server/;
    push @ignore_list_final, qr/^loaded base policy bank/;
    push @ignore_list_final, qr/^\d+\.From:/;
    push @ignore_list_final, qr/^Syslog (retries|warnings)/;
    push @ignore_list_final, qr/^smtp connection cache/;
    push @ignore_list_final, qr/^smtp cmd> /;
    push @ignore_list_final, qr/^smtp session/;
    push @ignore_list_final, qr/^Ignoring stale PID file/;
    push @ignore_list_final, qr/^mime_decode_preamble/;
    push @ignore_list_final, qr/^doing banned check for/;
    push @ignore_list_final, qr/^open_on_specific_fd/;
    push @ignore_list_final, qr/^reparenting /;
    push @ignore_list_final, qr/^Issued a new pseudo part: /;
    push @ignore_list_final, qr/^run_command: /;
    push @ignore_list_final, qr/^result line from file/;
    push @ignore_list_final, qr/^Charging /;
    push @ignore_list_final, qr/^check_for_banned /;
    push @ignore_list_final, qr/^Extracting mime components$/;
    push @ignore_list_final, qr/^response to /;
    push @ignore_list_final, qr/^File-type of /;
    push @ignore_list_final, qr/^Skip admin notification, /;
    push @ignore_list_final, qr/^run_av: /;
    push @ignore_list_final, qr/^string_to_mime_entity /;
    push @ignore_list_final, qr/^ndn_needed=/;
    push @ignore_list_final, qr/^sending RCPT TO:/;
    push @ignore_list_final, qr/^decode_parts: /;
    push @ignore_list_final, qr/^decompose_part: /;
    push @ignore_list_final, qr/^setting body type: /;
    push @ignore_list_final, qr/^mime_decode_epilogue: /;
    push @ignore_list_final, qr/^string_to_mime_entity: /;
    push @ignore_list_final, qr/^at the END handler: /;
    push @ignore_list_final, qr/^Amavis::.* called$/;
    push @ignore_list_final, qr/^Amavis::.* close,/;
    push @ignore_list_final, qr/^dkim: /; # XXX provide stats
    push @ignore_list_final, qr/^collect banned table/;
    push @ignore_list_final, qr/^collect_results from/;
    push @ignore_list_final, qr/^blocking contents category is/;
    push @ignore_list_final, qr/^running file\(/;
    push @ignore_list_final, qr/^Found av scanner/;
    push @ignore_list_final, qr/^Found myself/;
    push @ignore_list_final, qr/^mail_via_smtp/;
    push @ignore_list_final, qr/^switch_to_client_time/;
    push @ignore_list_final, qr/^parse_message_id/;
    push @ignore_list_final, qr/^parse_received: /;
    push @ignore_list_final, qr/^parse_ip_address_from_received: /;
    push @ignore_list_final, qr/^fish_out_ip_from_received: /;
    push @ignore_list_final, qr/^Waiting for the process \S+ to terminate/;
    push @ignore_list_final, qr/^Valid PID file \(younger than sys uptime/;
    push @ignore_list_final, qr/^Sending SIG\S+ to amavisd/;
    push @ignore_list_final, qr/^Can't send SIG\S+ to process/;
    push @ignore_list_final, qr/^killing process/;
    push @ignore_list_final, qr/^no need to kill process/;
    push @ignore_list_final, qr/^process .* is still alive/;
    push @ignore_list_final, qr/^Daemon \[\d+\] terminated by SIG/;
    push @ignore_list_final, qr/^storage and lookups will use .* to SQL/;
    push @ignore_list_final, qr/^idle_proc, /;
    push @ignore_list_final, qr/^switch_to_my_time/;
    push @ignore_list_final, qr/^TempDir::strip: /;
    push @ignore_list_final, qr/^rmdir_recursively/;
    push @ignore_list_final, qr/^sending [SL]MTP response/;
    push @ignore_list_final, qr/^prolong_timer/;
    push @ignore_list_final, qr/^process_request:/;
    push @ignore_list_final, qr/^exiting process_request/;
    push @ignore_list_final, qr/^post_process_request_hook: /;
    push @ignore_list_final, qr/^SMTP session over/;
    push @ignore_list_final, qr/^updating snmp variables/;
    push @ignore_list_final, qr/^best_try_originator_ip/;
    push @ignore_list_final, qr/^mail checking ended: /; # log level 2
    push @ignore_list_final, qr/^The amavisd daemon is already running/;
    push @ignore_list_final, qr/^AUTH not needed/;
    push @ignore_list_final, qr/^load: \d+ %, total idle/;
    push @ignore_list_final, qr/^policy protocol: [^=]+=\S+(?:,\S+)*$/; # allow "policy protocol: INVALID ..." later
    push @ignore_list_final, qr/^penpals: /;
    push @ignore_list_final, qr/^Not calling virus scanners, no files to scan in/;
    push @ignore_list_final, qr/^local delivery: /;
    push @ignore_list_final, qr/^run_as_subprocess: child process \S*: Broken pipe/;
    push @ignore_list_final, qr/^initializing Mail::SpamAssassin/;
    push @ignore_list_final, qr/^Error reading mail header section/; # seems to occur gen. due to perl getline() bug
    push @ignore_list_final, qr/^flatten_and_tidy_dir/;
    push @ignore_list_final, qr/^do_7zip: member/;
    push @ignore_list_final, qr/^Expanding \S+ archive/;
    push @ignore_list_final, qr/^files_to_scan:/;
    push @ignore_list_final, qr/^Unzipping p\d+/;
    push @ignore_list_final, qr/^writing mail text to SQL/;
    push @ignore_list_final, qr/^strip_tempdir/;
    push @ignore_list_final, qr/^no parts, file/;
    push @ignore_list_final, qr/^warnsender_with_pass/;
    push @ignore_list_final, qr/^RETURNED FROM SA check/;
    push @ignore_list_final, qr/^mime_traverse: /;
    push @ignore_list_final, qr/^do_spam: /;
    push @ignore_list_final, qr/^prepare_tempdir: /;
    push @ignore_list_final, qr/^check_header: /;
    push @ignore_list_final, qr/^skip admin notification/;
    push @ignore_list_final, qr/^do_executable: not a/;
    push @ignore_list_final, qr/^Skip spam admin notification, no administrators$/;
    push @ignore_list_final, qr/^skip banned check for/;
    push @ignore_list_final, qr/^is_outgoing /;
    push @ignore_list_final, qr/^NO Disclaimer/;
    push @ignore_list_final, qr/^Using \(\S+\) on file/;
    push @ignore_list_final, qr/^no anti-spam code loaded/;
    push @ignore_list_final, qr/^entered child_init_hook/;
    push @ignore_list_final, qr/^body type/;
    push @ignore_list_final, qr/^establish_or_refresh/;
    push @ignore_list_final, qr/^get_body_digest/;
    push @ignore_list_final, qr/^ask_daemon_internal/;
    push @ignore_list_final, qr/^Turning AV infection into a spam report, name already accounted for/;
    push @ignore_list_final, qr/^Calling virus scanners/;
    push @ignore_list_final, qr/^timer stopped after /;
    push @ignore_list_final, qr/^virus_presence /;
    push @ignore_list_final, qr/^cache entry /;
    push @ignore_list_final, qr/^generate_mail_id /;
    push @ignore_list_final, qr/^Load low precedence policybank/;
    push @ignore_list_final, qr/^warm restart on /; # XXX could be placed instartup info
    push @ignore_list_final, qr/^Signalling a SIGHUP to a running daemon/;
    push @ignore_list_final, qr/^Deleting db files /;
    push @ignore_list_final, qr/^address modified \(/;
    push @ignore_list_final, qr/^Request: AM\.PDP /;
    push @ignore_list_final, qr/^DSPAM result: /;
    push @ignore_list_final, qr/^bind to \//;
    push @ignore_list_final, qr/^ZMQ enabled: /;

    push @ignore_list_final, qr/^Inserting header field: X-Amavis-Hold: /;
    push @ignore_list_final, qr/^Decoding of .* failed, leaving it unpacked: /;

    # various forms of "Using ..."
    # more specific, interesting variants already captured: search "Using"
    push @ignore_list_final, qr/^Using \(.*\) on dir:/;
    push @ignore_list_final, qr/^Using [^:]+: \(built-in interface\)/;
    push @ignore_list_final, qr/^Using \(.*\): /;
    push @ignore_list_final, qr/: sleeping for /;
    push @ignore_list_final, qr/creating socket by /;

    # unanchored
    push @ignore_list_final, qr/\bRUSAGE\b/;
    push @ignore_list_final, qr/: Sending .* to UNIX socket/;
    push @ignore_list_final, qr/^lookup_ip_acl/;
    push @ignore_list_final, qr/^lookup_acl/;
    push @ignore_list_final, qr/^lookup_hash/;
    push @ignore_list_final, qr/^lookup_re/;
    push @ignore_list_final, qr/^lookup_ldap/;
    push @ignore_list_final, qr/^lookup_sql_field.* result=[YN]$/;
    push @ignore_list_final, qr/^lookup .* does not match$/;
    push @ignore_list_final, qr/^lookup [[(]/;
    push @ignore_list_final, qr/^lookup => /;
    push @ignore_list_final, qr/^lookup: /;
    push @ignore_list_final, qr/^save_info_preliminary/; # log level 4
    push @ignore_list_final, qr/^save_info_final/;       # log level 4
    push @ignore_list_final, qr/^sql: /;
    push @ignore_list_final, qr/^sql_storage: retrying/;
    push @ignore_list_final, qr/^sql flush: /;
    push @ignore_list_final, qr/^sql print/;
    push @ignore_list_final, qr/^sql begin transaction/;
    push @ignore_list_final, qr/^sql rollback/;
    push @ignore_list_final, qr/^mail_via_sql: /;
    push @ignore_list_final, qr/^CALLING SA check$/;
    push @ignore_list_final, qr/^calling SA parse,/;
    push @ignore_list_final, qr/^timer set to \d+/;
    push @ignore_list_final, qr/^query_keys/;
    push @ignore_list_final, qr/^find_or_save_addr: /;
    push @ignore_list_final, qr/^header: /;
    push @ignore_list_final, qr/^DO_QUARANTINE, /;
    push @ignore_list_final, qr/^DEBUG_ONESHOT: /;
    push @ignore_list_final, qr/^TempDir::/;
    push @ignore_list_final, qr/^check_mail_begin_task: /;
    push @ignore_list_final, qr/^program: .*?(anomy|altermime|disclaimer).*? said: /; # log_level 2
    push @ignore_list_final, qr/^body (?:type|hash): /;
    push @ignore_list_final, qr/^\d+\.From: <.*>, \d+.Mail_From:/;
    push @ignore_list_final, qr/^The amavisd daemon is (?:apparently )?not running/;
    push @ignore_list_final, qr/^rw_loop/;
    push @ignore_list_final, qr/^[SL]MTP[><]/;
    push @ignore_list_final, qr/^[SL]MTP response for/;
    push @ignore_list_final, qr/^dsn:/i, # DSN or dsn
        push @ignore_list_final, qr/^enqueue: /;
    push @ignore_list_final, qr/^write_header: /;
    push @ignore_list_final, qr/^banned check: /;
    push @ignore_list_final, qr/^child_finish_hook/;
    push @ignore_list_final, qr/^inspect_dsn:/;
    push @ignore_list_final, qr/^client IP address unknown/;
    push @ignore_list_final, qr/^final_destiny/;
    push @ignore_list_final, qr/^one_response_for_all/;
    push @ignore_list_final, qr/^headers CLUSTERING/;
    push @ignore_list_final, qr/^notif=/;
    push @ignore_list_final, qr/^\(about to connect/;
    push @ignore_list_final, qr/^Original mail size/;
    push @ignore_list_final, qr/^TempDir removal/;
    push @ignore_list_final, qr/^Issued a new file name/;
    push @ignore_list_final, qr/^starting banned checks/;
    push @ignore_list_final, qr/^skip admin notification/;
    push @ignore_list_final, qr/^do_notify_and_quarantine - done/;
    push @ignore_list_final, qr/^do_[a-zA-Z]+.* done$/i;
    push @ignore_list_final, qr/^Remote host presents itself as:/;
    push @ignore_list_final, qr/^connect_to_ldap/;
    push @ignore_list_final, qr/^connect_to_sql: trying /;
    push @ignore_list_final, qr/^ldap begin_work/;
    push @ignore_list_final, qr/^Connecting to LDAP server/;
    push @ignore_list_final, qr/^loaded base policy bank/;
    push @ignore_list_final, qr/^\d+\.From:/;
    push @ignore_list_final, qr/^Syslog (retries|warnings)/;
    push @ignore_list_final, qr/^smtp connection cache/;
    push @ignore_list_final, qr/^smtp cmd> /;
    push @ignore_list_final, qr/^smtp session/;
    push @ignore_list_final, qr/^Ignoring stale PID file/;
    push @ignore_list_final, qr/^mime_decode_preamble/;
    push @ignore_list_final, qr/^doing banned check for/;
    push @ignore_list_final, qr/^open_on_specific_fd/;
    push @ignore_list_final, qr/^reparenting /;
    push @ignore_list_final, qr/^Issued a new pseudo part: /;
    push @ignore_list_final, qr/^run_command: /;
    push @ignore_list_final, qr/^result line from file/;
    push @ignore_list_final, qr/^Charging /;
    push @ignore_list_final, qr/^check_for_banned /;
    push @ignore_list_final, qr/^Extracting mime components$/;
    push @ignore_list_final, qr/^response to /;
    push @ignore_list_final, qr/^File-type of /;
    push @ignore_list_final, qr/^Skip admin notification, /;
    push @ignore_list_final, qr/^run_av: /;
    push @ignore_list_final, qr/^string_to_mime_entity /;
    push @ignore_list_final, qr/^ndn_needed=/;
    push @ignore_list_final, qr/^sending RCPT TO:/;
    push @ignore_list_final, qr/^decode_parts: /;
    push @ignore_list_final, qr/^decompose_part: /;
    push @ignore_list_final, qr/^setting body type: /;
    push @ignore_list_final, qr/^mime_decode_epilogue: /;
    push @ignore_list_final, qr/^string_to_mime_entity: /;
    push @ignore_list_final, qr/^at the END handler: /;
    push @ignore_list_final, qr/^Amavis::.* called$/;
    push @ignore_list_final, qr/^Amavis::.* close,/;
    push @ignore_list_final, qr/^dkim: /; # XXX provide stats
    push @ignore_list_final, qr/^collect banned table/;
    push @ignore_list_final, qr/^collect_results from/;
    push @ignore_list_final, qr/^blocking contents category is/;
    push @ignore_list_final, qr/^running file\(/;
    push @ignore_list_final, qr/^Found av scanner/;
    push @ignore_list_final, qr/^Found myself/;
    push @ignore_list_final, qr/^mail_via_smtp/;
    push @ignore_list_final, qr/^switch_to_client_time/;
    push @ignore_list_final, qr/^parse_message_id/;
    push @ignore_list_final, qr/^parse_received: /;
    push @ignore_list_final, qr/^parse_ip_address_from_received: /;
    push @ignore_list_final, qr/^fish_out_ip_from_received: /;
    push @ignore_list_final, qr/^Waiting for the process \S+ to terminate/;
    push @ignore_list_final, qr/^Valid PID file \(younger than sys uptime/;
    push @ignore_list_final, qr/^Sending SIG\S+ to amavisd/;
    push @ignore_list_final, qr/^Can't send SIG\S+ to process/;
    push @ignore_list_final, qr/^killing process/;
    push @ignore_list_final, qr/^no need to kill process/;
    push @ignore_list_final, qr/^process .* is still alive/;
    push @ignore_list_final, qr/^Daemon \[\d+\] terminated by SIG/;
    push @ignore_list_final, qr/^storage and lookups will use .* to SQL/;
    push @ignore_list_final, qr/^idle_proc, /;
    push @ignore_list_final, qr/^switch_to_my_time/;
    push @ignore_list_final, qr/^TempDir::strip: /;
    push @ignore_list_final, qr/^rmdir_recursively/;
    push @ignore_list_final, qr/^sending [SL]MTP response/;
    push @ignore_list_final, qr/^prolong_timer/;
    push @ignore_list_final, qr/^process_request:/;
    push @ignore_list_final, qr/^exiting process_request/;
    push @ignore_list_final, qr/^post_process_request_hook: /;
    push @ignore_list_final, qr/^SMTP session over/;
    push @ignore_list_final, qr/^updating snmp variables/;
    push @ignore_list_final, qr/^best_try_originator_ip/;
    push @ignore_list_final, qr/^mail checking ended: /; # log level 2
    push @ignore_list_final, qr/^The amavisd daemon is already running/;
    push @ignore_list_final, qr/^AUTH not needed/;
    push @ignore_list_final, qr/^load: \d+ %, total idle/;
    push @ignore_list_final, qr/^policy protocol: [^=]+=\S+(?:,\S+)*$/; # allow "policy protocol: INVALID ..." later
    push @ignore_list_final, qr/^penpals: /;
    push @ignore_list_final, qr/^Not calling virus scanners, no files to scan in/;
    push @ignore_list_final, qr/^local delivery: /;
    push @ignore_list_final, qr/^run_as_subprocess: child process \S*: Broken pipe/;
    push @ignore_list_final, qr/^initializing Mail::SpamAssassin/;
    push @ignore_list_final, qr/^Error reading mail header section/; # seems to occur gen. due to perl getline() bug
    push @ignore_list_final, qr/^flatten_and_tidy_dir/;
    push @ignore_list_final, qr/^do_7zip: member/;
    push @ignore_list_final, qr/^Expanding \S+ archive/;
    push @ignore_list_final, qr/^files_to_scan:/;
    push @ignore_list_final, qr/^Unzipping p\d+/;
    push @ignore_list_final, qr/^writing mail text to SQL/;
    push @ignore_list_final, qr/^strip_tempdir/;
    push @ignore_list_final, qr/^no parts, file/;
    push @ignore_list_final, qr/^warnsender_with_pass/;
    push @ignore_list_final, qr/^RETURNED FROM SA check/;
    push @ignore_list_final, qr/^mime_traverse: /;
    push @ignore_list_final, qr/^do_spam: /;
    push @ignore_list_final, qr/^prepare_tempdir: /;
    push @ignore_list_final, qr/^check_header: /;
    push @ignore_list_final, qr/^skip admin notification/;
    push @ignore_list_final, qr/^do_executable: not a/;
    push @ignore_list_final, qr/^Skip spam admin notification, no administrators$/;
    push @ignore_list_final, qr/^skip banned check for/;
    push @ignore_list_final, qr/^is_outgoing /;
    push @ignore_list_final, qr/^NO Disclaimer/;
    push @ignore_list_final, qr/^Using \(\S+\) on file/;
    push @ignore_list_final, qr/^no anti-spam code loaded/;
    push @ignore_list_final, qr/^entered child_init_hook/;
    push @ignore_list_final, qr/^body type/;
    push @ignore_list_final, qr/^establish_or_refresh/;
    push @ignore_list_final, qr/^get_body_digest/;
    push @ignore_list_final, qr/^ask_daemon_internal/;
    push @ignore_list_final, qr/^Turning AV infection into a spam report, name already accounted for/;
    push @ignore_list_final, qr/^Calling virus scanners/;
    push @ignore_list_final, qr/^timer stopped after /;
    push @ignore_list_final, qr/^virus_presence /;
    push @ignore_list_final, qr/^cache entry /;
    push @ignore_list_final, qr/^generate_mail_id /;
    push @ignore_list_final, qr/^Load low precedence policybank/;
    push @ignore_list_final, qr/^warm restart on /; # XXX could be placed instartup info
    push @ignore_list_final, qr/^Signalling a SIGHUP to a running daemon/;
    push @ignore_list_final, qr/^Deleting db files /;
    push @ignore_list_final, qr/^address modified \(/;
    push @ignore_list_final, qr/^Request: AM\.PDP /;
    push @ignore_list_final, qr/^DSPAM result: /;
    push @ignore_list_final, qr/^bind to \//;
    push @ignore_list_final, qr/^ZMQ enabled: /;

    push @ignore_list_final, qr/^Inserting header field: X-Amavis-Hold: /;
    push @ignore_list_final, qr/^Decoding of .* failed, leaving it unpacked: /;

    # various forms of "Using ..."
    # more specific, interesting variants already captured: search "Using"
    push @ignore_list_final, qr/^Using \(.*\) on dir:/;
    push @ignore_list_final, qr/^Using [^:]+: \(built-in interface\)/;
    push @ignore_list_final, qr/^Using \(.*\): /;
    push @ignore_list_final, qr/: sleeping for /;
    push @ignore_list_final, qr/creating socket by /;

    # unanchored
    push @ignore_list_final, qr/\bRUSAGE\b/;
    push @ignore_list_final, qr/: Sending .* to UNIX socket/;
}
