language: java
jdk:
  - openjdk8
git:
  submodules: false
#os:
#  - linux
#  - osx

# Cache settings
cache:
  timeout: 600
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/perl5/
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - perlbrew clean
env: ORG_GRADLE_PROJECT_downloadIdeaSources=false

# Override default install process on TravisCI
# Avoid default `gradlew assemble` execution. Be explicit about it on the `script` section.
# More info: https://github.com/travis-ci/travis-ci/issues/8667
before_install:
  - perlbrew list
  - perlbrew install --verbose perl-5.26.2 --notest --noman || true
  - perlbrew lib create perl-5.26.2@test_mojo
  - perlbrew exec -q --with perl-5.26.2@test_mojo cpanm --notest Mojolicious
  - perlbrew list
install: true
script:
  - ./gradlew test
after_success:
  - ./gradlew coveralls

