{
  parserClass="com.perl5.lang.perl.parser.PerlParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Perl"
  psiImplClassSuffix="Impl"
  psiPackage="com.perl5.lang.perl.psi"
  psiImplPackage="com.perl5.lang.perl.psi.impl"

  elementTypeHolderClass="com.perl5.lang.perl.lexer.PerlElementTypes"
  elementTypeClass="com.perl5.lang.perl.PerlElementType"
  tokenTypeClass="com.perl5.lang.perl.PerlTokenType"

  tokens=[
    PERL_BAD_CHARACTER
    PERL_COMMENT
    PERL_COMMENT_BLOCK
    PERL_POD

    PERL_NEWLINE

    PERL_MULTILINE_MARKER
    PERL_MULTILINE_XML
    PERL_MULTILINE_HTML

    PERL_DQ_STRING
    PERL_SQ_STRING

    PERL_NUMBER
    PERL_STATIC_METHOD_CALL
    PERL_INSTANCE_METHOD_CALL
    PERL_VARIABLE_SCALAR
    PERL_VARIABLE_ARRAY
    PERL_VARIABLE_HASH
    PERL_VARIABLE_GLOB
    PERL_VARIABLE_SCALAR_BUILT_IN
    PERL_VARIABLE_ARRAY_BUILT_IN
    PERL_VARIABLE_HASH_BUILT_IN
    PERL_VARIABLE_GLOB_BUILT_IN
    PERL_FUNCTION
    PERL_FUNCTION_BUILT_IN
    PERL_PACKAGE
    PERL_PACKAGE_BUILT_IN
    PERL_PACKAGE_BUILT_IN_PRAGMA
    PERL_PACKAGE_BUILT_IN_DEPRECATED
    PERL_OPERATOR
    PERL_DEREFERENCE
    PERL_DEPACKAGE
    PERL_COMMA
    PERL_LBRACK
    PERL_RBRACK
    PERL_LPAREN
    PERL_RPAREN

    PERL_LBRACE
    PERL_RBRACE

    PERL_SEMI
  ]

}

perlFile ::= item_*

private item_ ::= PERL_POD | PERL_COMMENT | PERL_COMMENT_BLOCK | PERL_BAD_CHARACTER | script_item
private script_item ::= (script_block | any_item)* PERL_SEMI
private any_item ::= PERL_NEWLINE | PERL_MULTILINE_MARKER | PERL_MULTILINE_XML | PERL_MULTILINE_HTML | PERL_DQ_STRING | PERL_SQ_STRING | PERL_NUMBER | PERL_STATIC_METHOD_CALL | PERL_INSTANCE_METHOD_CALL | PERL_VARIABLE_SCALAR | PERL_VARIABLE_ARRAY | PERL_VARIABLE_HASH | PERL_VARIABLE_GLOB | PERL_VARIABLE_SCALAR_BUILT_IN | PERL_VARIABLE_ARRAY_BUILT_IN | PERL_VARIABLE_HASH_BUILT_IN | PERL_VARIABLE_GLOB_BUILT_IN | PERL_FUNCTION | PERL_FUNCTION_BUILT_IN | PERL_PACKAGE | PERL_PACKAGE_BUILT_IN | PERL_PACKAGE_BUILT_IN_PRAGMA | PERL_PACKAGE_BUILT_IN_DEPRECATED | PERL_OPERATOR | PERL_DEREFERENCE | PERL_DEPACKAGE | PERL_COMMA | PERL_LBRACK | PERL_RBRACK | PERL_LPAREN | PERL_RPAREN | script_block
private script_block ::= PERL_LBRACE any_item PERL_RBRACE
