Simple text

=head1 first header

Simple text

=head2 second header
X<second header>

Simple text

=head3 Third header
X<third B<header> index>

Simple text

=head4 Fourth C<header>
X<fourth header index>

Indexed paragraph text
X<paragraph index>

Indexed long paragraph text Indexed long paragraph text Indexed long paragraph text Indexed long paragraph text Indexed long paragraph text
Indexed long paragraph text Indexed long paragraph text Indexed long paragraph text Indexed long paragraph text Indexed long paragraph text
Indexed long paragraph text Indexed long paragraph text Indexed long paragraph text Indexed long paragraph text Indexed long paragraph text
X<long paragraph index>

=attr someattr

Simple text

=method somemethod

Simple text

=func somefunc

Simple text

=unknown bullshit

Simple text

=encoding utf8

Simple text

=for html test html

=begin html

Some html

=end html
