/* The following code was generated by JFlex 1.4.3 on 26.08.15 18:20 */

/*
    Copyright 2015 Alexandr Evstigneev

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/
package com.perl5.lang.perl.lexer;

import com.intellij.psi.TokenType;
import com.intellij.psi.tree.IElementType;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 26.08.15 18:20 from the specification file
 * <tt>C:/Repository/Perl5-IDEA/src/com/perl5/lang/perl/lexer/PerlString.flex</tt>
 */
public abstract class PerlStringLexerGenerated extends PerlBaseLexer
{
  /**
   * lexical states
   */
  public static final int YYINITIAL = 0;
  public static final int LEX_ESCAPED = 2;
  /**
   * initial size of the lookahead buffer
   */
  private static final int ZZ_BUFFERSIZE = 16384;
  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   * at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
          0, 0, 1, 1
  };

  /**
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED =
          "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\27\1\50" +
                  "\1\42\1\41\1\37\1\30\1\7\2\0\1\36\1\11\1\32\1\22" +
                  "\1\13\1\35\1\15\1\21\10\14\1\6\1\34\1\23\1\24\1\25" +
                  "\1\33\1\40\4\17\1\10\1\17\24\4\1\45\1\51\1\46\1\5" +
                  "\1\12\1\47\1\17\1\20\2\17\1\10\1\17\21\4\1\16\2\4" +
                  "\1\43\1\31\1\44\1\26\uff81\0";

  /**
   * Translates characters to character classes
   */
  private static final char[] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);
  private static final String ZZ_ACTION_PACKED_0 =
          "\2\0\2\1\1\2\1\3\1\4\1\5\1\6\1\7" +
                  "\1\10\1\11\2\12\1\13\1\14\1\15\1\16\1\17" +
                  "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27" +
                  "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37" +
                  "\1\40\1\41\1\42\2\0\1\43\1\44\1\45\1\0" +
                  "\1\46\1\47\1\4\2\47\3\4\1\50\1\51\1\52" +
                  "\1\0\1\53\1\54\1\55\1\56\1\57\1\60\1\61" +
                  "\1\62\1\63\2\0\1\44\1\0\1\47\1\64\3\47" +
                  "\1\0\1\65";
  /**
   * Translates DFA states to action switch labels.
   */
  private static final int[] ZZ_ACTION = zzUnpackAction();
  private static final String ZZ_ROWMAP_PACKED_0 =
          "\0\0\0\52\0\124\0\176\0\124\0\250\0\322\0\374" +
                  "\0\u0126\0\124\0\u0150\0\u017a\0\u01a4\0\u01ce\0\u01f8\0\u0222" +
                  "\0\u024c\0\u0276\0\124\0\u02a0\0\u02ca\0\u02f4\0\124\0\124" +
                  "\0\124\0\124\0\124\0\124\0\124\0\u031e\0\124\0\124" +
                  "\0\124\0\124\0\124\0\124\0\124\0\124\0\u0348\0\u0372" +
                  "\0\374\0\u039c\0\124\0\u03c6\0\u03f0\0\u041a\0\u0444\0\u046e" +
                  "\0\u0498\0\u04c2\0\u04ec\0\u0516\0\u0540\0\124\0\124\0\u056a" +
                  "\0\124\0\124\0\124\0\124\0\124\0\124\0\124\0\u0594" +
                  "\0\u0594\0\u05be\0\u0126\0\u05e8\0\u0612\0\u0612\0\124\0\u063c" +
                  "\0\u04c2\0\u04ec\0\u0540\0\124";
  /**
   * Translates a state to a row index in the transition table
   */
  private static final int[] ZZ_ROWMAP = zzUnpackRowMap();
  private static final String ZZ_TRANS_PACKED_0 =
          "\1\3\1\4\1\5\1\6\1\7\1\10\1\11\1\12" +
                  "\1\7\1\13\1\7\1\14\1\15\1\16\3\7\1\15" +
                  "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26" +
                  "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36" +
                  "\1\3\1\37\1\40\1\41\1\42\1\43\1\44\1\45" +
                  "\52\46\54\0\1\5\52\0\1\6\52\0\1\7\1\0" +
                  "\1\47\1\50\1\7\1\0\1\7\1\0\6\7\34\0" +
                  "\1\51\3\0\1\51\1\0\1\51\1\0\6\51\36\0" +
                  "\1\52\54\0\1\53\50\0\1\54\2\0\1\55\2\56" +
                  "\3\0\1\56\34\0\1\7\1\0\1\47\1\50\1\57" +
                  "\1\0\1\60\1\61\2\15\3\7\1\15\34\0\1\7" +
                  "\1\0\1\47\1\50\1\57\1\0\1\60\1\61\2\15" +
                  "\1\62\1\7\1\63\1\15\34\0\1\64\3\0\1\64" +
                  "\1\0\1\64\1\0\6\64\1\65\2\0\1\66\47\0" +
                  "\1\67\1\70\52\0\1\71\1\72\50\0\1\73\52\0" +
                  "\1\74\53\0\1\75\52\0\1\76\62\0\1\77\15\0" +
                  "\1\100\47\0\1\101\3\0\1\101\1\0\1\101\1\0" +
                  "\6\101\34\0\1\102\1\0\1\103\1\104\1\102\1\0" +
                  "\1\102\1\0\6\102\41\0\1\105\1\106\1\0\2\106" +
                  "\3\0\1\106\1\105\42\0\1\107\46\0\1\54\1\0" +
                  "\1\56\1\0\2\56\3\0\1\56\34\0\1\7\1\0" +
                  "\1\47\1\50\1\7\1\105\1\110\1\0\2\110\3\7" +
                  "\1\110\1\105\33\0\1\7\1\0\1\47\1\50\1\57" +
                  "\1\0\1\60\1\61\2\60\3\7\1\60\40\0\1\54" +
                  "\3\0\2\56\3\0\1\56\34\0\1\7\1\0\1\47" +
                  "\1\50\1\111\1\0\1\7\1\0\2\111\1\7\3\111" +
                  "\34\0\1\7\1\0\1\47\1\50\1\7\1\0\1\7" +
                  "\1\0\1\7\1\112\3\7\1\112\34\0\1\64\3\0" +
                  "\1\64\1\0\1\64\1\0\6\64\34\0\1\64\3\0" +
                  "\1\64\1\0\1\64\1\0\6\64\1\113\54\0\1\114" +
                  "\30\0\1\101\1\0\1\47\1\50\1\101\1\0\1\101" +
                  "\1\0\6\101\34\0\1\102\1\0\1\47\1\50\1\102" +
                  "\1\0\1\102\1\0\6\102\34\0\1\102\3\0\1\102" +
                  "\1\0\1\102\1\0\6\102\42\0\1\106\1\0\2\106" +
                  "\3\0\1\106\34\0\1\7\1\0\1\47\1\50\1\7" +
                  "\1\0\1\110\1\0\2\110\3\7\1\110\30\0";
  /**
   * The transition table of the DFA
   */
  private static final int[] ZZ_TRANS = zzUnpackTrans();
  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
          "Unkown internal scanner error",
          "Error: could not match input",
          "Error: pushback value was too large"
  };
  private static final String ZZ_ATTRIBUTE_PACKED_0 =
          "\2\0\1\11\1\1\1\11\4\1\1\11\10\1\1\11" +
                  "\3\1\7\11\1\1\10\11\2\0\2\1\1\11\1\0" +
                  "\11\1\2\11\1\0\7\11\2\1\2\0\1\1\1\0" +
                  "\1\1\1\11\3\1\1\0\1\11";
  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int[] ZZ_ATTRIBUTE = zzUnpackAttribute();
  private static java.io.Reader zzReader = null; // Fake
  /**
   * the current state of the DFA
   */
  private int zzState;
  /**
   * the current lexical state
   */
  private int zzLexicalState = YYINITIAL;
  /**
   * this buffer contains the current text to be matched and is
   * the source of the yytext() string
   */
  private CharSequence zzBuffer = "";
  /**
   * this buffer may contains the current text array to be matched when it is cheap to acquire it
   */
  private char[] zzBufferArray;
  /**
   * the textposition at the last accepting state
   */
  private int zzMarkedPos;
  /**
   * the textposition at the last state to be included in yytext
   */
  private int zzPushbackPos;
  /**
   * the current text position in the buffer
   */
  private int zzCurrentPos;
  /**
   * startRead marks the beginning of the yytext() string in the buffer
   */
  private int zzStartRead;
  /**
   * endRead marks the last character in the buffer, that has been read
   * from input
   */
  private int zzEndRead;
  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;
  /**
   * zzAtEOF == true <=> the scanner is at the EOF
   */
  private boolean zzAtEOF;

  public PerlStringLexerGenerated(java.io.Reader in)
  {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public PerlStringLexerGenerated(java.io.InputStream in)
  {
    this(new java.io.InputStreamReader(in));
  }

  private static int[] zzUnpackAction()
  {
    int[] result = new int[76];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int[] result)
  {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l)
    {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  private static int[] zzUnpackRowMap()
  {
    int[] result = new int[76];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int[] result)
  {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l)
    {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  private static int[] zzUnpackTrans()
  {
    int[] result = new int[1638];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int[] result)
  {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l)
    {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  private static int[] zzUnpackAttribute()
  {
    int[] result = new int[76];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int[] result)
  {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l)
    {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Unpacks the compressed character translation table.
   *
   * @param packed the packed character translation table
   * @return the unpacked character translation table
   */
  private static char[] zzUnpackCMap(String packed)
  {
    char[] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 110)
    {
      int count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public CharSequence getBuffer()
  {
    return zzBuffer;
  }

  public char[] getBufferArray()
  {
    return zzBufferArray;
  }

  public int getBufferEnd()
  {
    return zzEndRead;
  }

  public int getNextTokenStart()
  {
    return zzMarkedPos;
  }

  public boolean isLastToken()
  {
    return zzMarkedPos == zzEndRead;
  }

  public final int getTokenStart()
  {
    return zzStartRead;
  }

  /* user code: */
  //fixme this must be in skeleton
  public void setTokenStart(int position)
  {
    zzCurrentPos = zzStartRead = position;
  }

  public final int getTokenEnd()
  {
    return getTokenStart() + yylength();
  }

  public void setTokenEnd(int position)
  {
    zzMarkedPos = position;
  }

  public void reset(CharSequence buffer, int start, int end, int initialState)
  {
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException
  {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public int yystate()
  {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState)
  {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext()
  {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos)
  {
    return zzBufferArray != null ? zzBufferArray[zzStartRead + pos] : zzBuffer.charAt(zzStartRead + pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength()
  {
    return zzMarkedPos - zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   * <p/>
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   * <p/>
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param errorCode the code of the errormessage to display
   */
  private void zzScanError(int errorCode)
  {
    String message;
    try
    {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e)
    {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)
  {
    if (number > yylength())
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return the next token
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char[] zzCMapL = ZZ_CMAP;

    int[] zzTransL = ZZ_TRANS;
    int[] zzRowMapL = ZZ_ROWMAP;
    int[] zzAttrL = ZZ_ATTRIBUTE;

    while (true)
    {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction:
      {
        while (true)
        {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF)
          {
            zzInput = YYEOF;
            break zzForAction;
          } else
          {
            // store back cached positions
            zzCurrentPos = zzCurrentPosL;
            zzMarkedPos = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL = zzCurrentPos;
            zzMarkedPosL = zzMarkedPos;
            zzBufferL = zzBuffer;
            zzEndReadL = zzEndRead;
            if (eof)
            {
              zzInput = YYEOF;
              break zzForAction;
            } else
            {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[zzRowMapL[zzState] + zzCMapL[zzInput]];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ((zzAttributes & 1) == 1)
          {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ((zzAttributes & 8) == 8) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction])
      {
        case 22:
        {
          return OPERATOR_DIV;
        }
        case 54:
          break;
        case 10:
        {
          return NUMBER_SIMPLE;
        }
        case 55:
          break;
        case 44:
        {
          return OPERATOR_RE;
        }
        case 56:
          break;
        case 29:
        {
          return LEFT_BRACKET;
        }
        case 57:
          break;
        case 47:
        {
          return OPERATOR_AND;
        }
        case 58:
          break;
        case 16:
        {
          return OPERATOR_NOT;
        }
        case 59:
          break;
        case 1:
        {
          return STRING_CONTENT;
        }
        case 60:
          break;
        case 9:
        {
          return OPERATOR_CONCAT;
        }
        case 61:
          break;
        case 21:
        {
          return SEMICOLON;
        }
        case 62:
          break;
        case 48:
        {
          return OPERATOR_OR;
        }
        case 63:
          break;
        case 19:
        {
          return OPERATOR_COMMA;
        }
        case 64:
          break;
        case 42:
        {
          return OPERATOR_SHIFT_LEFT;
        }
        case 65:
          break;
        case 3:
        {
          return TokenType.WHITE_SPACE;
        }
        case 66:
          break;
        case 45:
        {
          return OPERATOR_SHIFT_RIGHT;
        }
        case 67:
          break;
        case 5:
        {
          return OPERATOR_BITWISE_XOR;
        }
        case 68:
          break;
        case 39:
        {
          return NUMBER;
        }
        case 69:
          break;
        case 36:
        {
          return PACKAGE_IDENTIFIER;
        }
        case 70:
          break;
        case 49:
        {
          return SIGIL_SCALAR_INDEX;
        }
        case 71:
          break;
        case 34:
        {
          yybegin(YYINITIAL);
          return STRING_CONTENT;
        }
        case 72:
          break;
        case 37:
        {
          return OPERATOR_PLUS_PLUS;
        }
        case 73:
          break;
        case 2:
        {
          return TokenType.NEW_LINE_INDENT;
        }
        case 74:
          break;
        case 6:
        {
          return COLON;
        }
        case 75:
          break;
        case 43:
        {
          return OPERATOR_COMMA_ARROW;
        }
        case 76:
          break;
        case 25:
        {
          return SIGIL_ARRAY;
        }
        case 77:
          break;
        case 17:
        {
          return OPERATOR_BITWISE_AND;
        }
        case 78:
          break;
        case 15:
        {
          return OPERATOR_BITWISE_NOT;
        }
        case 79:
          break;
        case 13:
        {
          return OPERATOR_ASSIGN;
        }
        case 80:
          break;
        case 11:
        {
          return OPERATOR_MINUS;
        }
        case 81:
          break;
        case 41:
        {
          return OPERATOR_DEREFERENCE;
        }
        case 82:
          break;
        case 52:
        {
          return OPERATOR_HELLIP;
        }
        case 83:
          break;
        case 23:
        {
          return OPERATOR_MUL;
        }
        case 84:
          break;
        case 26:
        {
          return SIGIL_SCALAR;
        }
        case 85:
          break;
        case 27:
        {
          return LEFT_BRACE;
        }
        case 86:
          break;
        case 14:
        {
          return OPERATOR_GT_NUMERIC;
        }
        case 87:
          break;
        case 31:
        {
          return QUOTE_TICK;
        }
        case 88:
          break;
        case 38:
        {
          return OPERATOR_FLIP_FLOP;
        }
        case 89:
          break;
        case 30:
        {
          return RIGHT_BRACKET;
        }
        case 90:
          break;
        case 12:
        {
          return OPERATOR_LT_NUMERIC;
        }
        case 91:
          break;
        case 33:
        {
          yybegin(LEX_ESCAPED);
          return OPERATOR_REFERENCE;
        }
        case 92:
          break;
        case 51:
        {
          return parsePackage();
        }
        case 93:
          break;
        case 53:
        {
          return OPERATOR_CMP_NUMERIC;
        }
        case 94:
          break;
        case 24:
        {
          return OPERATOR_MOD;
        }
        case 95:
          break;
        case 7:
        {
          return QUOTE_SINGLE;
        }
        case 96:
          break;
        case 35:
        {
          return IDENTIFIER;
        }
        case 97:
          break;
        case 50:
        {
          return parsePackageCanonical();
        }
        case 98:
          break;
        case 46:
        {
          return OPERATOR_NOT_RE;
        }
        case 99:
          break;
        case 40:
        {
          return OPERATOR_MINUS_MINUS;
        }
        case 100:
          break;
        case 20:
        {
          return QUESTION;
        }
        case 101:
          break;
        case 8:
        {
          return OPERATOR_PLUS;
        }
        case 102:
          break;
        case 4:
        {
          return parseBarewordMinus();
        }
        case 103:
          break;
        case 32:
        {
          return QUOTE_DOUBLE;
        }
        case 104:
          break;
        case 28:
        {
          return RIGHT_BRACE;
        }
        case 105:
          break;
        case 18:
        {
          return OPERATOR_BITWISE_OR;
        }
        case 106:
          break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
