# Re-usable workflow for building project
name: "Project"

on:
  workflow_call:

jobs:
  build:
    name: "Build"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        language: [ 'java' ]

    env:
      ORG_GRADLE_PROJECT_downloadIdeaSources: false
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
      CI: GitHub

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Execute Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
          arguments: jar instrumentTest --console plain
