# re-usable workflow to run integration tests
name: Tests

on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
        description: 'Job name'
      results_suffix:
        required: true
        type: string
        description: 'Suffix for artifacts name: test results and coverage'
      os:
        required: true
        type: string
        description: 'Os to run on'
      configurators:
        required: true
        type: string
        description: 'Configurators to use for running tests'

jobs:
  integration:
    name: ${{ inputs.title }}
    runs-on: ${{ inputs.os }}
    env:
      ORG_GRADLE_PROJECT_downloadIdeaSources: false
      CI: GitHub
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      PERL_TEST_VERSION: 5.36.0
      TEST_PERL_MODULES: Mojolicious HURRICUP/Devel-Camelcadedb-v2023.1.tar.gz Devel::Cover JSON App::Prove::Plugin::PassEnv TAP::Formatter::Camelcade Devel::NYTProf Perl::Tidy Perl::Critic B::Debug Types::Serialiser
      PERL_CONFIGURATORS: ${{ inputs.configurators }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Install Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ env.PERL_TEST_VERSION }}

      - name: Configure Perl
        shell: cmd
        run: cpanm --notest  ${{ env.TEST_PERL_MODULES }}

      - name: Run Tests
        uses: gradle/gradle-build-action@v2
        env:
          WITH_COVERAGE: ${{ env.COVERALLS_REPO_TOKEN && 'true' || 'false' }}
          TEST_SYSTEM_PERL_INTERPRETER_PATH: C:/hostedtoolcache/windows/perl/${{ env.PERL_TEST_VERSION }}-thr/x64/bin/perl.exe
        with:
          cache-read-only: true
          arguments: test -PintegrationTests=1 --console plain

      - name: Upload Tests Results
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-results-${{ inputs.results_suffix }}
          path: |
            **/build/test-results/*
            **/build/reports/tests/*

      - name: Upload Coverage Data
        if: ${{ env.COVERALLS_REPO_TOKEN }}
        uses: actions/upload-artifact@v3
        with:
          name: integration-tests-coverage-${{ inputs.results_suffix }}
          path: |
            **/jacoco/*.exec
