# re-usable workflow to run light tests
name: Light Tests

on:
  workflow_call:

jobs:
  build-plugins:
    name: Light
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_downloadIdeaSources: false
      CI: GitHub
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
      WITH_COVERAGE: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Run Tests
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true
          arguments: test -PlightTests=1 --console plain

      - name: Upload Tests Results
        uses: actions/upload-artifact@v3
        with:
          name: light-test-results
          path: |
            **/build/test-results/*
            **/build/reports/tests/*

      - name: Upload Coverage Data
        uses: actions/upload-artifact@v3
        with:
          name: light-tests-coverage
          path: |
            **/jacoco/*.exec

