# Re-usable workflow for project analysis with qodana
name: Qodana

on:
  workflow_call:

env:
  ORG_GRADLE_PROJECT_downloadIdeaSources: false
  CI: GitHub
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
  SPACE_USER: ${{ secrets.SPACE_NIGHTLY_USERNAME }}
  SPACE_KEY: ${{ secrets.SPACE_NIGHTLY_KEY }}
  QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2026.1.0
        env:
          QODANA_LINTER: ${{ env.QODANA_TOKEN == '' && 'jetbrains/qodana-jvm-community' || 'jetbrains/qodana-jvm' }}
        with:
          use-caches: false
          args: --baseline,.qodana/qodana.sarif.json,--linter,${{ env.QODANA_LINTER }},--property,idea.kotlin.plugin.use.k2=false,--env,SPACE_USER=${{ env.SPACE_USER }},--env,SPACE_KEY=${{ env.SPACE_KEY }},--env,GITHUB_TOKEN=${{ env.GITHUB_TOKEN }}

      - name: Remove results with undefined physicalLocation
        run: |
          jq '.runs[].results |= map(select(.locations != null and (.locations[] | .physicalLocation != null)))' \
            ${{ runner.temp }}/qodana/results/qodana.sarif.json > filtered_sarif.json && \
          mv filtered_sarif.json ${{ runner.temp }}/qodana/results/qodana.sarif.json
        shell: bash

      - uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json